authors:
  wangyantong:
    name: 王衍童 # Author name
    description: 华东师范大学X-lab # Author description
    avatar: https://avatars.githubusercontent.com/u/135088663?u=7619171319865b8b2a9c7a2b0c716d21872dc8a7&v=4 # Author avatar
